### ISSUE TITLE
python Vs R results, 

### ISSUE THREAD

**Issue by kputta** [bbalasub1/glmnet_python#45]
Hi,

For some reason the results from R have different cvsd compared to results from this python package. Do I need to do something else to match lambda.1se ?

If you see in below plot py_cvm matches with cvm ( coming from R ) but that is not the case with cvlo and cvup because of different cvsd and that effects lambda.1se choice ? 

I checked couple of time on my end and I dont see anything, am I missing something obvious ?
  
![image](https://user-images.githubusercontent.com/9323468/70184670-4ecae480-16b6-11ea-8342-a1c04e7b7661.png)

**Comment by bbalasub1** [comment]
That does not seem right.

How many rows of data are you using? My guess is there is a sqrt(n) missing
in one of the two.

**Comment by kputta** [comment]
I am using 4286397  X  38

and versions:

python: 3.7.2
scipy: 1.2.1
numpy: 1.16.3
pandas: 0.24.2

**Comment by bbalasub1** [comment]
Thanks. What nfolds are you using?

**Comment by kputta** [comment]
10


Best,
Kaushik

**Comment by bbalasub1** [comment]
Which model are you using? elnet seems to be coded right. The possible classes are: elnet, lognet, multnet, mrelnet, fishnet.

**Comment by kputta** [comment]
I am using mostly default args:
grouped = True 

infact just this line:
cvfit = cvglmnet(x = X_train.values, y = y_train.values, ptype = 'mse', nfolds=10)

**Comment by bbalasub1** [comment]
There was an overwrite in the Fortran routines called by glmnet.py that was causing this. Instead of passing by reference, I am copying the weights before passing. This seems to fix it, and I am getting a match between R and python versions. Please verify and let me know if you find any further problems. 

* For verification, I matched the foldid between R and python versions prior to the cross-validation step and compared the cvup, cvm, and cvlo. Since R uses a random permutation every time and foldid changes, you would need to hard code the foldid into both codes and match them. Also python uses a 0 index  while R uses a 1 index -- so ensure that you subtract 1 from python foldid when you hard code it!

**Comment by kputta** [comment]
Thanks
